theme: jekyll-theme-cayman
title: Klarna's Hello World Challenge: How To Develop A Bot
description: This is a tutorial for the Swedish Hello World! non-profit aiming to promote digital creativity. With the help of this guide you will develop a chat bot for either Kik or Telegram.
