theme: jekyll-theme-cayman
markdown: rdiscount
title: Hello World - Klarna
description: This is a tutorial for the Swedish [Hello World!](https://helloworld.se/) non-profit aiming to promote digital creativity. With the help of this guide you will develop a chat bot for either [Kik](https://www.kik.com/) or [Telegram](https://telegram.org/).
