theme: jekyll-theme-minimal
title: How To Develop A Chat Bot
description: This is a tutorial created for the Swedish Hello World! non-profit aiming to promote digital creativity. With the help of this guide you will develop a chat bot for either Kik or Telegram.
